{% set name = "casa_formats_io" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/casa-formats-io-{{ version }}.tar.gz
  sha256: f2267ec1c49f8790024dbdff89001fdaa429c19eb01315b071d2682e60848c1d

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - setuptools-scm
    - wheel
    - numpy
    - pip
  run:
    - python
    - astropy >=4.0
    - dask-core >=2.0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - casa_formats_io
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://casa-formats-io.readthedocs.org
  summary: Dask-based reader for CASA data
  license: LGPL-2.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - keflavich
    - mwcraig
    - astrofrog-conda-forge
