{% set name = "casa_formats_io" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 169423d17799eefbcecd433ffb9a86e85470357977833a14048b58750d4ce26e

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv
  number: 4

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - setuptools-scm
    - wheel
    - numpy
    - pip
  run:
    - python
    - astropy-base >=4.0
    - dask-core >=2.0

test:
  imports:
    - casa_formats_io
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://casa-formats-io.readthedocs.org
  summary: Dask-based reader for CASA data
  license: LGPL-2.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - keflavich
    - mwcraig
    - astrofrog
